# goal
string name
float64 duration
trajectory_msgs/JointTrajectoryPoint goal_joint
bool train
bool visualize
bool execute
bool control
---
#result
bool success
trajectory_msgs/JointTrajectory plan
---