sequenceDiagram
    participant User
    participant LFDPipeline
    participant LFDRecorder
    participant LFDTrainer
    participant LFDStorage
    participant LFDPlanner
    participant LFDMethod
    participant MoveitUtil

    User->>LFDPipeline: run()
    Note over User,LFDPipeline: action: /lfd_pipeline 
    activate LFDPipeline

    LFDPipeline->>LFDRecorder: run(demo_name)
    activate LFDRecorder
    loop Until robot starts moving
        LFDRecorder->>MoveitUtil: currentJointState()
        MoveitUtil-->>LFDRecorder: joint state
        LFDRecorder->>LFDRecorder: robotHasMoved()
    end
    loop Until recording is complete
        LFDRecorder->>MoveitUtil: currentJointState()
        MoveitUtil-->>LFDRecorder: joint state
        LFDRecorder->>MoveitUtil: visualizeTrajectory()
    end
    LFDRecorder->>LFDStorage: save()
    Note over LFDRecorder,LFDStorage: topic: /save_demonstration
    LFDRecorder-->>LFDPipeline: success
    deactivate LFDRecorder

    LFDPipeline->>LFDTrainer: run()
    activate LFDTrainer
    LFDTrainer->>LFDStorage: loadDemonstration()
    Note over LFDTrainer,LFDStorage: service: /get_demonstration
    LFDStorage-->>LFDTrainer: demonstration
    LFDTrainer->>LFDMethod: trainDemonstration()
    note over LFDTrainer,LFDMethod: service: /train_demonstration
    LFDTrainer-->>LFDPipeline: success
    deactivate LFDTrainer

    LFDPipeline->>LFDPlanner: runViz()
    activate LFDPlanner
    LFDPlanner->>MoveitUtil: currentJointState()
    MoveitUtil-->>LFDPlanner: start state
    LFDPlanner->>LFDMethod: getPlan()
    note over LFDPlanner,LFDMethod: service: /plan_lfd
    LFDMethod-->>LFDPlanner: planned trajectory
    LFDPlanner->>MoveitUtil: visualizeTrajectory()
    LFDPlanner-->>LFDPipeline: planned trajectory
    deactivate LFDPlanner

    LFDPipeline->>LFDPlanner: runExec()
    activate LFDPlanner
    LFDPlanner->>MoveitUtil: currentJointState()
    MoveitUtil-->>LFDPlanner: start state
    LFDPlanner->>LFDMethod: getPlan()
    note over LFDPlanner,LFDMethod: service: /plan_lfd
    LFDMethod-->>LFDPlanner: planned trajectory
    LFDPlanner->>MoveitUtil: executePlan()
    MoveitUtil-->>LFDPlanner: execution success
    LFDPlanner-->>LFDPipeline: planned trajectory
    deactivate LFDPlanner

    LFDPipeline-->>User: pipeline result
    deactivate LFDPipeline