classDiagram
    class DMPWrapper {
        +train()
        +plan()
        +train_callback()
        +plan_callback()
    }

    class DMPBBOWrapper {
        +train()
        +plan()
    }

    DMPWrapper <|-- DMPBBOWrapper
