
classDiagram
    class  CameraProgram {
        +locate_target()
        +trigger()
    }

    class MotionProgram {
        +configure()
        +set_target()
    }

    class RobotProgram {
        +ik
        +fk
        +move()
        +pose_to_joint()
        +joint_to_pose()
        +add_gripper()
    }

    class DMPProgram {
        +configure()
        +train()
        +visualize()
        +execute()
    }

    %% ABB Program
    class YumiProgram {
        +add_gripper()
        +write_motion()
        +execute_motion()
        +move_generic()
    }

    class YumiL {
        +move()
    }

    class YumiR {
        +move()
    }

    class YumiGripper {
        +moveto()
        +grasp()
    }

    %% Franka Program
    class FR3Program {
        +add_gripper()
        +move()
    }

    class FrankaGripper {
        +moveto()
        +grasp()
    }

    %% Util
    class ForwardKinematics {
        +ee_frame
        +get_pose()
    }

    class InverseKinematics {
        +ee_frame
        +request_ik()
    }
    %% 
    class ProgramRunner {
        +set_camera()
        +set_motion_mode()
        +configure_motion()
        +move()
        +locate_target()
    }

    class YumiRunner {
        +set_motion_mode()
        +configure_motion()
        +configure_l_motion()
        +configure_r_motion()
        +locate_l_target()
        +locate_r_target()
        +move_l()
        +move_r()
        +move()
    }

    class RobotGripper {
        +moveto()
        +grasp()
    }

    ProgramRunner <|-- YumiRunner

    ProgramRunner ..> CameraProgram
    ProgramRunner ..> MotionProgram
    ProgramRunner ..> RobotProgram

    MotionProgram <|-- DMPProgram
    RobotProgram <|-- YumiProgram
    RobotProgram <|-- FR3Program
    YumiProgram <|-- YumiL 
    YumiProgram <|-- YumiR
    RobotGripper <|-- YumiGripper
    RobotGripper <|-- FrankaGripper
    RobotProgram ..> ForwardKinematics
    RobotProgram ..> InverseKinematics
    YumiL ..> YumiGripper
    YumiR ..> YumiGripper
    %% YumiProgram ..> YumiGripper
    FR3Program ..> FrankaGripper