sequenceDiagram
    participant User
    participant PR as ProgramRunner
    participant RP as RobotProgram
    participant MP as DMPProgram
    participant CP as CameraProgram
    participant RG as RobotGripper
    %% participant FK as ForwardKinematics
    participant IK as InverseKinematics

    User->>PR: initialize(robot)
    activate PR
    Note over User,PR: initialize the program with certain params
    PR->>RP: create robot program
    PR->>MP: set_motion_mode(dmp)
    User->>PR: set_camera()
    PR->>CP: initialize()
    
    User->>PR: configure_motion(params)
    PR->>MP: configure(params)
    deactivate PR

    User->>PR: locate_target(alias)
    activate PR
    Note over User,PR: Locate a target via camera
    PR->>CP: locate_target(alias)
    Note over CP: through CameraServer
    CP-->>PR: target pose
    PR->>RP: pose_to_joint(target_pose)
    RP->>IK: request_ik(target_pose)
    IK-->>RP: joint configuration
    RP-->>PR: target joint configuration
    PR->>MP: set_target(target_joint_config)
    deactivate PR


    User->>PR: configure_motion(demo_name)
    activate PR  
    Note over User,PR: Move to target via a demonstration
    PR->>MP: train(demo_name)  
    note over MP: through LFDPipeline
    User->>PR: move()
    PR->>RP: move()
    RP->>MP: visualize/execute()
    note over MP: through LFDPipeline
    MP-->>RP: motion plan
    RP-->>PR: success
    deactivate PR
    
    User->>PR: gripper()
    activate PR
    Note over User,PR: actuate the gripper
    PR->>RG: moveto/grasp()
    deactivate PR