classDiagram

    class TrajectorySmoother {
        +read_demonstration()
        +filter_demonstration()
        +run()
        -config
        -robot
    }

   class TrajectoryOptimizer {
        +run()
        -robot
        -config
    }

    class SingleOptimizer {
        -tolerances
        -ntimings
        +run()
    }
    


    class RobotConfig {
        +parse()
        +add_initial_guess()
        +add_solver()
        +demo
        +thr_translation
        +thr_translation
        +bspline_order
        +overlap
        +vel_bound
        +acc_bound
        +jerk_bound
        +coeff_duration
        +coeff_jerk
        +coeff_joint_cp_error
        +tol_translation
        +tol_rotation
        +init_guess_cps
        +waypoints_ts
        +solver
    }

    class DrakeRobot {
        -urdf_path
        -ee_frame
        +visualize(q)
    }
    

    class IKSolver {
        +run(position, orientation, q_init=None)
        -visualize(q)
        -config
        -robot
    }
    %% SingleOptimizer --|> TrajectoryOptimizer
    TrajectoryOptimizer <|-- SingleOptimizer
    TrajectorySmoother ..> TrajectoryOptimizer
    TrajectorySmoother ..> SingleOptimizer
    TrajectorySmoother ..> DrakeRobot
    TrajectorySmoother ..> RobotConfig
    IKSolver ..> DrakeRobot