classDiagram

    class TrajectorySmoother {
        +read_demonstration()
        +filter_demonstration()
        +run()
        -config
        -robot
    }

   class TrajectoryOptimizer {
        +run()
        -robot
        -config
    }

    class SingleOptimizer {
        -tolerances
        -ntimings
        +run()
    }
    


    class RobotConfig {
        +parse()
    }

    class DrakeRobot {
        -urdf_path
        -ee_frame
        +visualize(q)
    }
    

    class IKSolver {
        +run(position, orientation)
        -visualize()
        -config
        -robot
    }
    %% SingleOptimizer --|> TrajectoryOptimizer
    TrajectoryOptimizer <|-- SingleOptimizer
    TrajectorySmoother ..> TrajectoryOptimizer
    TrajectorySmoother ..> SingleOptimizer
    TrajectorySmoother ..> DrakeRobot
    TrajectorySmoother ..> RobotConfig
    IKSolver ..> DrakeRobot