sequenceDiagram
    participant User
    participant HandEye
    %% participant DataCollection
    participant CameraServer
    participant Camera
    participant MoveitUtil


    CameraServer->>Camera: connect()
    User->>HandEye: start calibration
    Note over User, HandEye: collect calibration data
    activate HandEye
    loop Until data collection is done
        MoveitUtil-->>HandEye: end-effector pose
        Note over MoveitUtil, HandEye: topic: /pose_state
        HandEye->>HandEye: read_robot_pose()
        HandEye->>CameraServer: read_camera_pose()
        activate CameraServer
        Note over HandEye, CameraServer: action: /camera_action
        %% CameraServer->>Camera: switch_job()
        CameraServer->>Camera: read()
        Camera-->>CameraServer: pose
        CameraServer-->>HandEye: raw pose
        deactivate CameraServer
        %% HandEye->>HandEye: read_camera_pose()
    end
    HandEye-->>User: calibration data
    deactivate HandEye

    User->>HandEye: calibrate
    activate HandEye
    Note over User, HandEye: solve calibration
    %% HandEye->>HandEye: solve()
    HandEye->>HandEye: calculate_transformation()
    HandEye-->>User: transformation config
    deactivate HandEye

    User->>CameraConfig: create config
    CameraConfig-->>Camera: update calibration config

    User->>CameraServer: locate(target)
    activate CameraServer
    Note over User, CameraServer: action: /camera_action
    CameraServer->>Camera: read(target)
    Camera-->>CameraServer: pose
    CameraServer-->>User: target pose in robot coordinates
    deactivate CameraServer
